name: Clone
on: workflow_dispatch

jobs:
  deploy:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd /pub/jphilip/
              rm -rf 389TProject5
              git clone https://github.com/unrealJune/389TProject5.git
              
              
