name: Clone
on: workflow_dispatch

jobs:
  deploy:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Remote SSH Commands
      uses: fifsky/ssh-action@v0.0.6
      with:
        command: |
          cd /pub/jphilip/
          rm -rf 389TProject5
          git clone https://github.com/unrealJune/389TProject5.git
        host: ${{ secrets.HOST }}
        user: jphilip
        pass: ${{ secrets.PASSWORD}}
              
